### ISSUE TITLE
Scheduled Scrubs

### ISSUE THREAD

**Issue by ylluminate** [cbreak-black/ZetaWatch#1]
Have you considered implementing a way to schedule and activate scrubs?

**Comment by cbreak-black** [comment]
I did consider interacting with pools, but most of those interactions require special permissions, which would need to be implemented in a way that doesn't lead to exploitable security holes. Scrubbing in a cron job seems to be a more reliable approach.

**Comment by ylluminate** [comment]
Hmmm, is there a reason that you can't use `cron` OR `launchd`?  

Might explore and chime in here: 
https://openzfsonosx.org/forum/viewtopic.php?f=24&t=2191

**Comment by cbreak-black** [comment]
ZetaWatch don't need to use cron, it is configured by the user directly. When you set up a cron job, or a launchd Agent / Daemon, those will be started on your behalf. Zeta Watch is intended to be purely read-only for now.

I was considering adding some useful interaction functionality such as import / export / mount / snapshot, but since those require elevated privileges that isn't likely to  happen any time soon.

**Comment by cbreak-black** [comment]
There are better options for timed scrubs, but I'm considering adding user initiated scrubbing.

**Comment by cbreak-black** [comment]
Manual scrubbing works now :) For automated ones, there are better utilities.
