### ISSUE TITLE
Appcast is behind GitHub release

### ISSUE THREAD

**Issue by vitorgalvao** [cbreak-black/ZetaWatch#18]
The app’s Sparkle appcast, located at https://zetawatch.the-color-black.net/download/2.0/appcast.xml, is at version 48. But [the current latest release](https://github.com/cbreak-black/ZetaWatch/releases/tag/r49) is at 49.

**Comment by cbreak-black** [comment]
Hey, I updated the appcast, but for 2.0, the last supported version is r48. Release r49 is for 2.1, which has a different appcast:
https://zetawatch.the-color-black.net/download/2.1/appcast.xml

Unfortunately, ZetaWatch relies on the zfs libraries, which are not ABI stable, and in some situations not even API stable. It'd be a bit annoying to support multiple ZFS versions because of that.

**Comment by vitorgalvao** [comment]
Thank you for the quick reply.

But there’s an error with that appcast: it tries (and fails) to download https://zetawatch.the-color-black.net/download/2.0/ZetaWatch-r49-0-g23683f.zip (`/2.0/`) when it should be https://zetawatch.the-color-black.net/download/2.1/ZetaWatch-r49-0-g23683f.zip (`/2.0/`).

And the `SUFeedURL` key is pointing to the old appcast. See https://github.com/cbreak-black/ZetaWatch/pull/19.

**Comment by cbreak-black** [comment]
Ah, yes, indeed, you're right. This value will be overwritten at runtime here:
https://github.com/cbreak-black/ZetaWatch/blob/master/ZetaWatch/ZetaWatchDelegate.mm#L97-L104
But you're right that it should be fixed, especially since this causes incorrect appcasts to be generated.
