### ISSUE TITLE
Is there a particular reason why ZetaWatch is not available as a Homebrew package? 

### ISSUE THREAD

**Issue by fad1** [cbreak-black/ZetaWatch#30]
Unsure if creating an issue is the right way to ask this...

**Comment by ideologysec** [comment]
I suspect it's because there's additional overhead required to maintain it (though not much  - it would be very cool to have it set up as a GitHub Action to publish to homebrew when a new version is released, for example).

Some info on how to do this for the maintainer:
https://extrawurst.medium.com/github-actions-homebrew-%EF%B8%8F-2789ae5023fd

If you were so enterprising, you could create the recipe yourself, since this is a versioned release setup and GitHub is easy to download from.

**Comment by cbreak-black** [comment]
I kind of left MacOS, so I'm not really putting in any effort into this project. Building it is a quite manual process though, and requires code signing, which can't be automated easily (since only a crazy person would upload the private keys to a build server). Also, I'm not convinced homebrewe is the right place for a GUI application.
