### ISSUE TITLE
Error reading pool configuration

### ISSUE THREAD

**Issue by greg-fischer** [cbreak-black/ZetaWatch#4]
Launched Zetawatch r13 (new install) getting an error "Error reading pool configuration" and the popup notification shows:
ZFS encountered an error: Internal nvlist structure dize does not match vdev_stat_t size.

This is on High Sierra 10.13.6, zfs on osx 1.7.4.

My pools are setup with most newer feature flags disabled to allow importing on older linux systems.  Just a guess, but maybe I need certain feature flags enabled?

**Comment by cbreak-black** [comment]
No, you just need to use OpenZFS 1.9. The library ABI changes all the time when they add new features, for example by adding new fields to structs, adding new enums values to enums or similar, which basically makes it impossible to support ZFS library versions that are too distinct.

If you want to use ZetaWatch with your old version of OpenZFS, you'll have to remove support for features and recompile it.

**Comment by greg-fischer** [comment]
Ok cool, that makes sense.  So when you release new ZetaWatch versions do you list which version of OpenZFS is supported?  
Thanks so much! I can't wait to use ZetaWatch. I've been watching your releases for months and haven't tried loading until now. You've come a long way on the features. Nice job!

**Comment by cbreak-black** [comment]
I usually release for the version I use myself, which should be close to the newest release version. I try to mention in releases when I switch for which version of ZFS I compile, so that the new releases are no longer compatible with the same version. Unfortunately, making ZetaWatch compatible is not always just a simple recompile, otherwise I'd offer more different versions.
